language: node_js
node_js:
- 'lts/*'
addons:
  apt:
    packages:
    - graphviz
deploy:
  provider: npm
  email: henri.bergius@iki.fi
  api_key:
    secure: Ij55oEAH47RgrvdWv3/dOZjvFeLOcUradffhu1JP4BJyuHqHt972ADtEk3qsAQeRKKrvkvU44py8Q2D1csS+tUgYZKpQmIGWUGqI8TgAAezmbKI3Xrj7x7BIgFC1vD3hbrCkhShBkAIZ14n7puJg3LTooRIUk3clsGoW72ItCBg=
  on:
    tags: true
    repo: noflo/noflo-graphviz
